<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>loginBtn</name>
   <tag></tag>
   <elementGuidId>559bbb31-2455-4025-a66e-d0b4028f09e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>4b61be21-b08e-4f3d-b177-bee5837e9c64</webElementGuid>
   </webElementProperties>
</WebElementEntity>
